#ifndef _TASK_H
#define _TASK_H

#define MAILBOX_SIZE 256
#define TASK_NAME_SIZE 256
#define ANSWER_COMPUTE_DURATION 5000
#define ANSWER_MESSAGE_SIZE 10000
#define ACK_COMPUTE_DURATION 100
#define ACK_MESSAGE_SIZE 10

#define BAD_ANSWER 100000
#define GOOD_ANSWER 0

#endif
